// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzz0LfPJI7Tgc-YB9dBc0eoRxJmOJCevY',
    appId: '1:985122543779:web:6e6fb8c1d7a93ee1874716',
    messagingSenderId: '985122543779',
    projectId: 'qldt-73c00',
    authDomain: 'qldt-73c00.firebaseapp.com',
    storageBucket: 'qldt-73c00.firebasestorage.app',
    measurementId: 'G-0V3L7BKNEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBukccU55x6uWEw_ezoqQTgE9rK4m1HY6Y',
    appId: '1:985122543779:android:7abf27032f123177874716',
    messagingSenderId: '985122543779',
    projectId: 'qldt-73c00',
    storageBucket: 'qldt-73c00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDDu9hkVUBMwhdTvrcu-hG0Rx3aYNMDWs',
    appId: '1:985122543779:ios:dff10e469415098c874716',
    messagingSenderId: '985122543779',
    projectId: 'qldt-73c00',
    storageBucket: 'qldt-73c00.firebasestorage.app',
    iosBundleId: 'com.example.qldt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDDu9hkVUBMwhdTvrcu-hG0Rx3aYNMDWs',
    appId: '1:985122543779:ios:dff10e469415098c874716',
    messagingSenderId: '985122543779',
    projectId: 'qldt-73c00',
    storageBucket: 'qldt-73c00.firebasestorage.app',
    iosBundleId: 'com.example.qldt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzz0LfPJI7Tgc-YB9dBc0eoRxJmOJCevY',
    appId: '1:985122543779:web:1abb33d32b478c93874716',
    messagingSenderId: '985122543779',
    projectId: 'qldt-73c00',
    authDomain: 'qldt-73c00.firebaseapp.com',
    storageBucket: 'qldt-73c00.firebasestorage.app',
    measurementId: 'G-6B9XQGCPNZ',
  );

}