// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjM-qeTfzLgbTzUnBq9rHMGVyyMVmkMBc',
    appId: '1:792382887500:web:c8cab43abe5da25ca906e9',
    messagingSenderId: '792382887500',
    projectId: 'qldt-new',
    authDomain: 'qldt-new.firebaseapp.com',
    storageBucket: 'qldt-new.firebasestorage.app',
    measurementId: 'G-52FDBVS1VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJdf61uWVA7r50pkJsmKUEKFZpeJltsNI',
    appId: '1:792382887500:android:a67365949a7a1ad8a906e9',
    messagingSenderId: '792382887500',
    projectId: 'qldt-new',
    storageBucket: 'qldt-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXNiCJa0Gca_rDX-JuBYJZTZ23p0QBgw0',
    appId: '1:792382887500:ios:434e1ee3e495055fa906e9',
    messagingSenderId: '792382887500',
    projectId: 'qldt-new',
    storageBucket: 'qldt-new.firebasestorage.app',
    iosBundleId: 'com.example.qldt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXNiCJa0Gca_rDX-JuBYJZTZ23p0QBgw0',
    appId: '1:792382887500:ios:434e1ee3e495055fa906e9',
    messagingSenderId: '792382887500',
    projectId: 'qldt-new',
    storageBucket: 'qldt-new.firebasestorage.app',
    iosBundleId: 'com.example.qldt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjM-qeTfzLgbTzUnBq9rHMGVyyMVmkMBc',
    appId: '1:792382887500:web:1c0fb29d9b7ce9e6a906e9',
    messagingSenderId: '792382887500',
    projectId: 'qldt-new',
    authDomain: 'qldt-new.firebaseapp.com',
    storageBucket: 'qldt-new.firebasestorage.app',
    measurementId: 'G-VMMQL2JKXQ',
  );

}